/* Decakila Libya — all interface copy, both languages.
   T.en and T.ar share one set of keys: add a string to both, then tag the
   element with data-i18n="key" or read it in a view with t("key").
   Loaded before the application script. */
window.DECAKILA_COPY = {
  en: {
    dir: "ltr", label: "العربية",
    skip: "Skip to content",
    navCountry: "Libya", navAuth: "Authorised distributor",
    navHome: "Home", navProducts: "Products", navServices: "Services", navAbout: "About us",
    navCta: "Request a quote",

    heroEyebrow: "Decakila · Libya",
    heroTitle: "Making fun life easier",
    heroLead: "Kitchen, home and personal-care appliances chosen for Libyan homes — 220–240V ready, stocked in depth, and backed after the sale.",
    heroCta: "Browse the catalogue",
    heroCta2: "Our services",
    statProducts: "products in catalogue",
    statCats: "product categories",
    statVolt: "220–240V · 50/60Hz",
    statVoltNote: "built for the Libyan grid",
    statParts: "spare parts stocked",

    catsEyebrow: "The range",
    catsTitle: "Seven ranges, one supplier",
    catsLead: "From a 2-litre air fryer to a 100-litre water heater — the full Decakila line, held locally and quoted the same day.",
    catsAll: "See every product",
    itemsWord: "items",

    featEyebrow: "Moving now",
    featTitle: "Popular this season",
    featLead: "A cross-section of the range with the specifications buyers ask for first.",
    featAll: "All products",

    promiseEyebrow: "Why Decakila",
    promiseTitle: "Appliances you can service, not replace",
    p1t: "Specified for here",
    p1b: "Every unit runs on 220–240V at 50/60Hz, with plug types and gas fittings matched to what is used in Libya.",
    p2t: "Parts on the shelf",
    p2b: "Jars, filters, blades, housings and heating elements are catalogued as products in their own right — a broken part is not a dead appliance.",
    p3t: "One number to call",
    p3b: "Warranty, service and replacement all run through the same team that sold you the unit.",

    ctaTitle: "Tell us what you need",
    ctaLead: "Retail, wholesale or a fit-out — send the model codes and we will come back with pricing and availability.",
    ctaBtn: "Request a quote",
    ctaAlt: "Talk to sales",

    prodEyebrow: "Catalogue",
    prodTitle: "Products",
    prodLead: "The current Decakila line for Libya. Filter by range or search by name, model code or specification.",
    searchPh: "Search products, model codes or specs…",
    all: "All products",
    resultsOne: "product",
    resultsMany: "products",
    noneTitle: "Nothing matched that search",
    noneBody: "Try a shorter term, a model code such as KEEC007B, or clear the filter.",
    clear: "Clear filters",
    more: "Show more products",
    quote: "Request quote",
    details: "Specifications",
    code: "Model",

    aboutEyebrow: "About us",
    aboutTitle: "The Decakila name in Libya",
    aboutLead: "We import, warehouse and support the Decakila appliance range for Libyan retailers, wholesalers and households.",
    aboutH1: "How we got here",
    aboutP1: "Decakila builds appliances for everyday life — the blender that runs every morning, the water heater that has to survive a hard winter, the fan that works all summer. We brought the brand to Libya because that is exactly what the market was missing: equipment priced for real households that still holds up in daily use.",
    aboutP2: "What began as a handful of kitchen lines has grown into the full catalogue you see here — cooking, cleaning, cooling, personal care, cookware and the spare parts that keep all of it running. Stock is held locally, so a retailer in Benghazi and a retailer in Tripoli order from the same shelf.",
    aboutH2: "How we judge quality",
    aboutQ1: "Electrical safety first", aboutQ1b: "Rated voltage, insulation class and protection rating are checked against the specification sheet before a shipment is accepted.",
    aboutQ2: "Tested on our own grid", aboutQ2b: "Units are run in on local supply — including the voltage dips a Libyan household actually sees — before they reach a shelf.",
    aboutQ3: "Materials that match the claim", aboutQ3b: "SUS304 where SUS304 is stated, PFOA-free coatings where they are promised, and thickness measured rather than assumed.",
    aboutH3: "What we hold ourselves to",
    v1t: "Honest specifications", v1b: "The wattage, capacity and material we publish are the ones printed on the unit. No rounding up.",
    v2t: "Availability over promises", v2b: "We quote what is in the warehouse today and say plainly when something is inbound.",
    v3t: "Support after the invoice", v3b: "A sale that ends at the door is not a sale we want. Service and parts are part of the price.",
    v4t: "Fair trade terms", v4b: "The same catalogue, the same conditions, whether you buy one unit or a container.",

    svcEyebrow: "Services",
    svcTitle: "What comes with the box",
    svcLead: "Buying an appliance is the easy part. These are the three things that decide whether it is still working in three years.",
    s1t: "Warranty cover", s1b: "Every appliance carries a manufacturer warranty against defects in materials and workmanship, registered to your invoice at the point of sale.",
    s1l1: "Covered from the invoice date", s1l2: "Repair or replacement at our discretion", s1l3: "Warranty travels with the appliance, not the buyer",
    s2t: "Customer support", s2b: "A technical team that knows the catalogue: setup, fault-finding, and a straight answer on whether something is worth repairing.",
    s2l1: "Phone and WhatsApp support", s2l2: "In-workshop diagnosis", s2l3: "Installation guidance for water heaters and gas units",
    s3t: "Genuine spare parts", s3b: "Blender jars, grinding filters, heating tubes, housings and brush heads held as catalogue items — matched to your exact model code.",
    s3l1: "Parts matched by model code", s3l2: "Original components only", s3l3: "Shipped nationwide",
    svcMoreTitle: "And the practical things",
    m1t: "Delivery across Libya", m1b: "Palletised freight to retailers and direct delivery to households in the main cities.",
    m2t: "Wholesale supply", m2b: "Container and pallet pricing for retailers, with the full catalogue available to order.",
    m3t: "Project fit-out", m3b: "Kitting out apartments, cafés or offices? Send the list and we will price the whole scope.",
    svcCta: "Start a request",

    quoteEyebrow: "Quote request", quoteTitle: "Request a price",
    qProduct: "Product", qName: "Your name", qPhone: "Phone number", qCity: "City", qQty: "Quantity", qNote: "Notes (optional)",
    qNotePh: "Delivery address, timing, anything else we should know.",
    qSubmit: "Send request", qCancel: "Cancel",
    qCity1: "Tripoli", qCity2: "Benghazi", qCity3: "Misrata", qCity4: "Sabha", qCity5: "Zawiya", qCity6: "Other",
    qDoneTitle: "Your request is ready",
    qDoneBody: "Send these details to our sales team and quote the reference — we confirm price and availability the same working day.",
    qRef: "Reference",
    qCopy: "Copy request details", qCopied: "Copied",
    qReach: "Sales:",
    qDoneClose: "Done",
    qErrName: "Please enter your name.", qErrPhone: "Please enter a phone number we can reach you on.",

    footBlurb: "Home, kitchen and personal-care appliances built for daily use — supplied, warranted and serviced across Libya.",
    footNav: "Pages", footCats: "Categories", footReach: "Get in touch",
    footAddr: "Tripoli · Benghazi · Misrata", footHours: "Sat–Thu, 9:00 – 18:00",
    footRights: "© 2026 Decakila Libya. All rights reserved.",
    footNote: "Specifications from the current Decakila catalogue and may change without notice."
  },
  ar: {
    dir: "rtl", label: "English",
    skip: "تخطَّ إلى المحتوى",
    navCountry: "ليبيا", navAuth: "الموزّع المعتمد",
    navHome: "الرئيسية", navProducts: "المنتجات", navServices: "الخدمات", navAbout: "من نحن",
    navCta: "اطلب عرض سعر",

    heroEyebrow: "ديكاكيلا · ليبيا",
    heroTitle: "حياة أسهل وأكثر متعة",
    heroLead: "أجهزة المطبخ والمنزل والعناية الشخصية مختارة للبيت الليبي — تعمل على 220–240 فولت، متوفّرة بكميات، ومدعومة بعد البيع.",
    heroCta: "تصفّح الكتالوج",
    heroCta2: "خدماتنا",
    statProducts: "منتج في الكتالوج",
    statCats: "أقسام رئيسية",
    statVolt: "220–240 فولت · 50/60 هرتز",
    statVoltNote: "مناسبة للشبكة الليبية",
    statParts: "قطعة غيار متوفّرة",

    catsEyebrow: "التشكيلة",
    catsTitle: "سبعة أقسام من مورّد واحد",
    catsLead: "من قلاية هوائية سعة 2 لتر إلى سخان مياه 100 لتر — تشكيلة ديكاكيلا كاملة، متوفّرة محليًا ويُسعّر طلبك في نفس اليوم.",
    catsAll: "استعرض كل المنتجات",
    itemsWord: "منتج",

    featEyebrow: "الأكثر طلبًا",
    featTitle: "مختارات هذا الموسم",
    featLead: "نماذج من التشكيلة مع المواصفات التي يسأل عنها المشتري أولًا.",
    featAll: "كل المنتجات",

    promiseEyebrow: "لماذا ديكاكيلا",
    promiseTitle: "أجهزة تُصان ولا تُستبدل",
    p1t: "مواصفات تناسبنا",
    p1b: "كل جهاز يعمل على 220–240 فولت بتردد 50/60 هرتز، بقوابس ووصلات غاز مطابقة للمستخدم في ليبيا.",
    p2t: "قطع الغيار جاهزة",
    p2b: "الأكواب والفلاتر والشفرات والهياكل وعناصر التسخين مدرجة في الكتالوج كمنتجات مستقلة — عطل قطعة لا يعني نهاية الجهاز.",
    p3t: "رقم واحد للتواصل",
    p3b: "الضمان والصيانة والاستبدال كلها عبر الفريق نفسه الذي باعك الجهاز.",

    ctaTitle: "أخبرنا بما تحتاجه",
    ctaLead: "تجزئة أو جملة أو تجهيز كامل — أرسل أكواد الموديلات ونعود إليك بالسعر والتوفّر.",
    ctaBtn: "اطلب عرض سعر",
    ctaAlt: "تحدّث مع المبيعات",

    prodEyebrow: "الكتالوج",
    prodTitle: "المنتجات",
    prodLead: "تشكيلة ديكاكيلا الحالية في ليبيا. صفِّ حسب القسم أو ابحث بالاسم أو كود الموديل أو المواصفة.",
    searchPh: "ابحث بالاسم أو كود الموديل أو المواصفة…",
    all: "كل المنتجات",
    resultsOne: "منتج",
    resultsMany: "منتج",
    noneTitle: "لا توجد نتائج مطابقة",
    noneBody: "جرّب كلمة أقصر، أو كود موديل مثل KEEC007B، أو ألغِ التصفية.",
    clear: "إلغاء التصفية",
    more: "عرض المزيد",
    quote: "اطلب عرض سعر",
    details: "المواصفات",
    code: "الموديل",

    aboutEyebrow: "من نحن",
    aboutTitle: "ديكاكيلا في ليبيا",
    aboutLead: "نستورد ونخزّن وندعم تشكيلة ديكاكيلا لأجهزة المنزل لتجار التجزئة والجملة والأسر في ليبيا.",
    aboutH1: "كيف بدأنا",
    aboutP1: "تصنع ديكاكيلا أجهزة للاستخدام اليومي — الخلاط الذي يعمل كل صباح، وسخان المياه الذي يجب أن يصمد في الشتاء، والمروحة التي لا تتوقف طوال الصيف. جلبنا العلامة إلى ليبيا لأن هذا تحديدًا ما كان ينقص السوق: أجهزة بسعر يناسب البيت الليبي وتتحمّل الاستعمال اليومي.",
    aboutP2: "بدأنا بعدد محدود من أجهزة المطبخ، واليوم لدينا الكتالوج كاملًا: الطهي والتنظيف والتبريد والعناية الشخصية وأواني المطبخ وقطع الغيار التي تُبقي كل ذلك يعمل. البضاعة مخزّنة محليًا، فيطلب تاجر بنغازي وتاجر طرابلس من المخزون نفسه.",
    aboutH2: "كيف نقيس الجودة",
    aboutQ1: "السلامة الكهربائية أولًا", aboutQ1b: "نتحقق من الجهد ودرجة العزل ودرجة الحماية مقابل ورقة المواصفات قبل قبول أي شحنة.",
    aboutQ2: "اختبار على شبكتنا", aboutQ2b: "تُشغَّل الأجهزة على التيار المحلي — بما في ذلك انخفاض الجهد الذي يحدث فعلًا في البيوت — قبل وصولها إلى الرف.",
    aboutQ3: "خامات مطابقة للوصف", aboutQ3b: "ستانلس 304 حيث يُذكر 304، وطلاء خالٍ من PFOA حيث يُوعد به، وسماكة تُقاس ولا تُفترض.",
    aboutH3: "ما نلتزم به",
    v1t: "مواصفات صادقة", v1b: "القدرة والسعة والخامة التي ننشرها هي المطبوعة على الجهاز نفسه، دون مبالغة.",
    v2t: "التوفّر قبل الوعود", v2b: "نسعّر ما هو موجود في المخزن اليوم، ونوضّح بصراحة ما هو في الطريق.",
    v3t: "دعم بعد الفاتورة", v3b: "البيع الذي ينتهي عند الباب ليس بيعًا نرغب فيه؛ الصيانة وقطع الغيار جزء من السعر.",
    v4t: "شروط تعامل عادلة", v4b: "نفس الكتالوج ونفس الشروط، سواء اشتريت جهازًا واحدًا أو حاوية كاملة.",

    svcEyebrow: "الخدمات",
    svcTitle: "ما يأتي مع الجهاز",
    svcLead: "الشراء هو الجزء السهل. هذه الأمور الثلاثة تحدّد إن كان الجهاز سيظل يعمل بعد ثلاث سنوات.",
    s1t: "الضمان", s1b: "كل جهاز يحمل ضمان المصنع ضد عيوب الخامات والتصنيع، ويُسجَّل على فاتورتك عند الشراء.",
    s1l1: "يبدأ من تاريخ الفاتورة", s1l2: "إصلاح أو استبدال حسب الحالة", s1l3: "الضمان يتبع الجهاز لا المشتري",
    s2t: "دعم العملاء", s2b: "فريق فني يعرف الكتالوج: التركيب، وتشخيص الأعطال، وإجابة واضحة عمّا إذا كان الإصلاح يستحق.",
    s2l1: "دعم عبر الهاتف وواتساب", s2l2: "تشخيص داخل الورشة", s2l3: "إرشاد لتركيب السخانات وأجهزة الغاز",
    s3t: "قطع غيار أصلية", s3b: "أكواب الخلاطات وفلاتر الطحن وعناصر التسخين والهياكل ورؤوس الفرشاة متوفّرة كأصناف في الكتالوج ومطابقة لكود موديلك.",
    s3l1: "مطابقة حسب كود الموديل", s3l2: "قطع أصلية فقط", s3l3: "شحن لكل المدن",
    svcMoreTitle: "وأمور عملية أخرى",
    m1t: "التوصيل داخل ليبيا", m1b: "شحن بالطبليات للتجار وتوصيل مباشر للمنازل في المدن الرئيسية.",
    m2t: "البيع بالجملة", m2b: "أسعار الحاوية والطبلية للتجار، مع إمكانية طلب الكتالوج كاملًا.",
    m3t: "تجهيز المشاريع", m3b: "تجهّز شققًا أو مقاهي أو مكاتب؟ أرسل القائمة ونسعّر لك المشروع كاملًا.",
    svcCta: "ابدأ طلبك",

    quoteEyebrow: "طلب عرض سعر", quoteTitle: "اطلب السعر",
    qProduct: "المنتج", qName: "الاسم", qPhone: "رقم الهاتف", qCity: "المدينة", qQty: "الكمية", qNote: "ملاحظات (اختياري)",
    qNotePh: "عنوان التسليم، الوقت المناسب، أو أي تفاصيل أخرى.",
    qSubmit: "إرسال الطلب", qCancel: "إلغاء",
    qCity1: "طرابلس", qCity2: "بنغازي", qCity3: "مصراتة", qCity4: "سبها", qCity5: "الزاوية", qCity6: "مدينة أخرى",
    qDoneTitle: "طلبك جاهز",
    qDoneBody: "أرسل هذه التفاصيل إلى فريق المبيعات مع ذكر رقم الطلب، ونؤكد لك السعر والتوفّر في نفس يوم العمل.",
    qRef: "رقم الطلب",
    qCopy: "نسخ تفاصيل الطلب", qCopied: "تم النسخ",
    qReach: "المبيعات:",
    qDoneClose: "تم",
    qErrName: "الرجاء إدخال الاسم.", qErrPhone: "الرجاء إدخال رقم هاتف للتواصل.",

    footBlurb: "أجهزة المنزل والمطبخ والعناية الشخصية للاستخدام اليومي — توريد وضمان وصيانة في كل ليبيا.",
    footNav: "الصفحات", footCats: "الأقسام", footReach: "تواصل معنا",
    footAddr: "طرابلس · بنغازي · مصراتة", footHours: "السبت–الخميس، 9:00 – 18:00",
    footRights: "© 2026 ديكاكيلا ليبيا. جميع الحقوق محفوظة.",
    footNote: "المواصفات مأخوذة من كتالوج ديكاكيلا الحالي وقابلة للتغيير دون إشعار."
  }
};
